jv_pg_pt_duration="1800" # programme duration in seconds "ex: 1800 for 30mins, all programme with duration < 30mins exlude"
listechainetv='{ "devices":[
{ "chainetv": "C192.api.telerama.fr", "nom": "TF1"},
{ "chainetv": "C4.api.telerama.fr", "nom": "France 2"},
{ "chainetv": "C80.api.telerama.fr", "nom": "France 3"},
{ "chainetv": "C34.api.telerama.fr", "nom": "Canal+"},
{ "chainetv": "C47.api.telerama.fr", "nom": "France 5"},
{ "chainetv": "C118.api.telerama.fr", "nom": "M6"},
{ "chainetv": "C111.api.telerama.fr", "nom": "Arte"},
{ "chainetv": "C445.api.telerama.fr", "nom": "C8"},
{ "chainetv": "C119.api.telerama.fr", "nom": "W9"},
{ "chainetv": "C195.api.telerama.fr", "nom": "TMC"},
{ "chainetv": "C446.api.telerama.fr", "nom": "TFX"},
{ "chainetv": "C444.api.telerama.fr", "nom": "NRJ12"},
{ "chainetv": "C234.api.telerama.fr", "nom": "LCP"},
{ "chainetv": "C78.api.telerama.fr", "nom": "France 4"},
{ "chainetv": "C481.api.telerama.fr", "nom": "BFM TV"},
{ "chainetv": "C226.api.telerama.fr", "nom": "CNEWS"},
{ "chainetv": "C458.api.telerama.fr", "nom": "CSTAR"},
{ "chainetv": "C482.api.telerama.fr", "nom": "Gulli"},
{ "chainetv": "C160.api.telerama.fr", "nom": "France o"},
{ "chainetv": "C1404.api.telerama.fr", "nom": "TF1 series films"},
{ "chainetv": "C1401.api.telerama.fr", "nom": "L\'Equipe"},
{ "chainetv": "C1403.api.telerama.fr", "nom": "6ter"},
{ "chainetv": "C1402.api.telerama.fr", "nom": "Numero 23"},
{ "chainetv": "C1400.api.telerama.fr", "nom": "RMC"},
{ "chainetv": "C1399.api.telerama.fr", "nom": "Cherie 25"},
{ "chainetv": "C112.api.telerama.fr", "nom": "LCI"},
{ "chainetv": "C2111.api.telerama.fr", "nom": "France info"},
{ "chainetv": "C145.api.telerama.fr", "nom": "Paris premiere"}
]}'
